auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_9.urls')),
]

story_9/urls.py
from django.contrib import admin
from django.urls import *
from .views import *

app_name='story_9'
urlpatterns = [
    path('', index, name='index'),
    path('login/', login_view, name='login'),
	path('logout/', logout_view, name='logout'),
	path('register/', register, name='register'),
]

story_9/models.py
from django.db import models

# Create your models here.

story_9/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

def index(request):
	if not request.user.is_authenticated:
		return render(request, 'login.html', {})
	return render(request, 'index.html', {})

def login_view(request):
	if request.method == "POST":
		username = request.POST["username"]
		password = request.POST["password"]
		user = authenticate(request, username=username, password=password)
		response = {"user" : user}
		if user is not None:
			login(request, user)
			return render(request, 'index.html', response)
		else:
			return render(request, 'login.html', {"message": "Invalid username or password."})

	return render(request, 'login.html', {"message": None})

def logout_view(request):
	logout(request)
	return render(request, 'login.html', {})

def register(request):
	if request.method == "POST":
		first_name = request.POST["first_name"]
		last_name = request.POST["last_name"]
		username = request.POST["username"]
		email = request.POST["email"]
		password = request.POST["password"]
		new_user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email, password=password)
		new_user.save()

		user = authenticate(request, username=username, password=password)
		login(request, user)
		response = {"user" : user}
		return render(request, 'login.html', response)

	return render(request, "register.html")

story_9/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<title>{% block title %} {% endblock %} - Login</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'acs/style.css' %}">
		<link href="https://fonts.googleapis.com/css?family=Raleway:700,800" rel="stylesheet">
	</head>

	<body class="flex-center">
		{% block body %}

		{% endblock %}
	</body>
</html>

story_9/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	Home
{% endblock %}

{% block body %}
	<h1 id="welcome-text">Hello, {{ user.first_name }}!</h1>
	<a href="{% url 'story_9:logout' %}"><button class="btn btn-danger">Logout</button></a>
{% endblock %}

story_9/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Login {% endblock %}

{% block body %}
	<div class="card shadow-lg">
		<h5 class="card-header">Login</h5>
		<div class="card-body">			
			{% if message %}
				<div class="alert alert-danger" role="alert">
					{{message}}
				</div>
			{% endif %}

			<form action="{% url 'story_9:login' %}" method="POST">
				{% csrf_token %}
				<div class="form-group">
					<label>Username</label>
					<input type="text" class="form-control" name="username" required>
				</div>
				<div class="form-group">
					<label>Password</label>
					<input type="password" class="form-control" name="password" required>
				</div>
				<div class="form-group">
					<input type="submit" class="btn btn-success" value="Login">
				</div>
				<small class="form-text">Don't have an account? <a href="{% url 'story_9:register' %}">Register</a></small>
			</form>	
		</div>
	</div>
{% endblock %}

story_9/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Register {% endblock %}

{% block body %}
	<div class="card shadow-lg">
		<h5 class="card-header">Register</h5>
		<div class="card-body">
			<form action="{% url 'story_9:register' %}" method="POST">
				{% csrf_token %}
				<div class="form-group">
					<label>First Name</label>
					<input type="text" class="form-control" name="first_name" required>
				</div>
				<div class="form-group">
					<label>Last Name</label>
					<input type="text" class="form-control" name="last_name" required>
				</div>
				<div class="form-group">
					<label>Username</label>
					<input type="text" class="form-control" name="username" required>
				</div>
				<div class="form-group">
					<label>Email</label>
					<input type="email" class="form-control" name="email" required>
				</div>
				<div class="form-group">
					<label>Password</label>
					<input type="password" class="form-control" name="password" required>
				</div>
				<div class="form-group">
					<input type="submit" class="btn btn-success" value="Register">
				</div>
			</form>	
		</div>
	</div>
{% endblock %}